cb_organization:
    path: /
    defaults: { _controller: CBOrganization:Veille:index }


cb_organization_view:
    path: /veille/{id}
    defaults: { _controller: CBOrganizationBundle:Veille:view }


